project:
  type: website
  output-dir: docs

# website:
#   title: "My Quarto Website"
#   sidebar:
#     search: true
#     contents:
#       - text: "Home"
#         href: index.qmd
#       - text: "Notebook"
#         href: notebooks/wrf_extract_wind.ipynb
# project:
#   type: website



website:
  title: "ustc"
  page-navigation: true
  navbar:
    #background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        href: tutorials.qmd
      - text: "How-To"
        href: howto.qmd
      - text: "Fundamentals"
        href: fundamentals.qmd
      - text: "Reference"
        href: reference.qmd


  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "基础"
        href: basics-summary.qmd
        contents:
          - index.qmd
          - python.qmd
          - text: "linux"
            href: linux.qmd          

      - section: "画图"
        contents:
          - text: "extract_wrf_站点wind"
            href: notebooks/wrf_extract_wind.ipynb
          - text: "extract_wrf_区域多种变量"
            href: notebooks/extractwrf_LC.ipynb
          - text: "extract_wrfchem_区域变量（近地面、柱浓度）"
            href: notebooks/extract_wrfchem.ipynb

          - text: "create_wrf_meic清单"
            href: notebooks/create_meic.ipynb

          - text: "plot_国控点臭氧"
            href: notebooks/国控站点画到地图上.ipynb

          - text: "plot_cartopy_map模板" 
            href: notebooks/cartopymap.ipynb 

          - text: "plot_ustc_Anhui_map模板"
            href: notebooks/ustc_plot_Anhuimap.ipynb  
          - text: "plot_ustc_Hefei_map模板"
            href: notebooks/ustc_plot_Hefeimap.ipynb              
          - text: "plot_相关性散点图"
            href: notebooks/相关性散点图.ipynb 
          - text: "plot_global_map模板" 
            href: notebooks/globalmap_v2.ipynb 

          - text: "plot_棒棒糖图" 
            href: https://www.tvhahn.com/posts/beautiful-plots-lollipop/


      - section: "AI"
        contents:
          - text: "人工智能时间序列预测" 
            href: https://github.com/thuml/Time-Series-Library/blob/main/tutorial/TimesNet_tutorial.ipynb


      - section: "数据处理"
        contents:
          - text: "era5数据" 
            href: notebooks/处理era5_1.ipynb 
          - custom-theme.qmd
      - acknowlegment.qmd
    tools:
      - icon: twitter
        href: https://twitter.com

      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com


  page-footer: 
    left: "Copyright 2024, Jingkai Xue" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/

  # page-footer:
  #   border: false

  # page-footer:
  #   background: light
  
  reader-mode: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# website:
#   back-to-top-navigation: true
#   title: "ustc"
#   page-navigation: true
#   sidebar:

#     contents:
#       - section: "First Section"
#         contents:
#           - text: "Notebook"    
#             href: notebooks/wrf_extract_wind.ipynb
#           - href: document2.qmd
#           - href: document3.qmd
#       - text: "---"
#       - section: "Second Section"
#         contents:
#           - href: document4.qmd
#           - href: document5.qmd
#           - href: document6.qmd

